blank_issues_enabled: false
contact_links:
  - name: 🐛 Bug report
    url: https://github.com/HXSecurity/DongTai-web/issues/new?assignees=piexlmax,exexute&labels=bug&projects=HXSecurity/DongTai/1&template=bug_report.yaml
    about: Report a bug to help us improve DongTai

  - name: 🚀 Feature request
    url: https://github.com/HXSecurity//DongTai-web/issues/new?assignees=piexlmax,exexute&labels=feature&projects=HXSecurity/DongTai/1&template=feature_request.yaml
    about: Suggest an idea for DongTai

  - name: ❓ Ask a question
    url: https://github.com/HXSecurity/DongTai/discussions/new?category=q-a
    about: Ask and discuss questions with other DongTai community members

  - name: 📚 Documentation
    url: https://hxsecurity.github.io/DongTaiDoc
    about: Check the documentation for help
