name: Deploy DongTai-Web to AWS

on:
  pull_request:
    branches: [ max-191 ]
  push:
    branches: [ max-191 ]

# concurrency:
#   group: dlc-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true
jobs:
  CheckDeadLinks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run: sudo npm install -g markdown-link-check
      - run: |
          for file in $(find . -name "*.md"); do
            markdown-link-check -c .github/workflows/config/.dlc.json -q "$file"
          done
  Deploy-To-Test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v1
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to AliyunRegistry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DONGTAI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.DONGTAI_DOCKERHUB_TOKEN }}
      
      - name: test and build
        run: |
          npm ci
          npm test
          npm run build --if-present

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            dongtai/dongtai-web-guoshun:1.9.0
            dongtai/dongtai-web-guoshun:latest
